### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by risaiwata** [risaiwata/protospace-35399#1]
# URL
https://protospace-35399.herokuapp.com/

**Comment by takumi0530** [comment]
@risaiwata さん、ご提出ありがとうございます‼︎　お待たせしてしまい、申し訳ございません。
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

##### **◾︎ユーザー管理機能**

- [x] **パスワードは確認用を含めて2回入力すること**
現状、入力する欄が1つしかありません。
<img width="331" alt="スクリーンショット 2021-04-20 14 21 57" src="https://user-images.githubusercontent.com/76197191/115342418-33964180-a1e5-11eb-9d60-1dd82cbdf6f7.png">

##### **◾︎一覧表示機能**

- [x] **ログイン・ログアウトの状態に関わらず、プロトタイプ一覧を閲覧できること**
現状、ログアウト状態ですと、プロトタイプ一覧を閲覧することができませんでした。
**※上記により、ログアウト状態での機能の動作確認ができておりません。次回ご提出時に確認させていただきます。**

##### **◾︎編集機能**

- [x] **空の入力欄がある場合は、編集できずにそのページに留まること**
現状、空の入力欄を作ってから保存を押すと、元々入っていた情報が全て消えてしまいます。

##### **◾︎コメント機能**

- [x] **正しくフォームを入力すると、コメントが投稿できること**
現状、コメントを入力し、送信ボタンを押してもコメントが反映されません。
**※上記により、コメント機能の動作確認ができておりません。次回ご提出時に確認させていただきます。**

##### **◾︎その他**

- [x] **ログアウト状態のユーザーは、プロトタイプ新規投稿ページ・プロトタイプ編集ページに遷移しようとすると、ログインページにリダイレクトされること**
新規投稿ページのみ遷移できてしまいます。

- [x] **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされること**
他のユーザーの編集ページへ遷移できてしまいます。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by takumi0530** [comment]
@risaiwata さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、再度修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

##### **◾︎一覧表示機能**

- [x] **ログイン・ログアウトの状態に関わらず、一覧表示されている画像およびプロトタイプ名をクリックすると、該当するプロトタイプの詳細ページへ遷移すること**

ログアウト状態ですと、プロトタイプをクリックするとエラーページに遷移してしまいます。
**※上記により、ログアウト状態での機能の動作確認ができておりません。次回ご提出時に確認させていただきます。**
<img width="673" alt="スクリーンショット 2021-04-21 10 19 39" src="https://user-images.githubusercontent.com/76197191/115483547-f0db7480-a28b-11eb-995d-a8fba606c9ea.png">

##### **◾︎コメント機能**

- [x] **フォームを空のまま投稿しようとすると、投稿できずにそのページに留まること**

新しく投稿した自身のコメントフォームに限り、空のまま投稿しようとするとエラーページに遷移してしまいます。
<img width="673" alt="スクリーンショット 2021-04-21 10 19 39" src="https://user-images.githubusercontent.com/76197191/115483662-2c763e80-a28c-11eb-89ba-666b66914491.png">

##### **◾︎その他**

- [x]  **ログアウト状態のユーザーであっても、トップページ・プロトタイプ詳細ページ・ユーザー詳細ページ・ユーザー新規登録ページ・ログインページには遷移できること**
プロトタイプ詳細ページ・ユーザー詳細ページに遷移しようとするとエラー画面に遷移してしまいます。


 

- [x] **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされること**
他のユーザーの編集ページへ遷移できてしまいます。


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by takumi0530** [comment]
@risaiwata さん、再度ご提出ありがとうございます‼︎
動作の確認をしたところ、改めて修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [x] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること**
ログイン状態で表示される、「こんにちは、●●さん」の部分をクリックすると、エラーページに遷移します。

<img width="420" alt="スクリーンショット 2021-04-21 12 49 27" src="https://user-images.githubusercontent.com/76197191/115494409-8da80d00-a2a0-11eb-9799-3ad138e8369e.png">


<img width="694" alt="スクリーンショット 2021-04-21 12 49 31" src="https://user-images.githubusercontent.com/76197191/115494369-76691f80-a2a0-11eb-9193-d1b966c9009c.png">


 

- [ ] **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされること**
他のユーザーの編集ページへ遷移できてしまいます。

https://user-images.githubusercontent.com/76197191/115494388-808b1e00-a2a0-11eb-9e83-7f41f5a606a6.mov



修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by takumi0530** [comment]
@risaiwata さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀
